name: First GitHub Action

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print a Message
        run: echo "Hello from GitHub Actions!"
